name: Build Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  push_to_registries:
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build dockerfile and push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            fabi281/gamehub:${{ github.run_number }}
            fabi281/gamehub:latest
      -
        name: Print tag
        run: echo "Tagged images with latest and $GITHUB_RUN_NUMBER"
